### ISSUE TITLE
Pro guard Optimize

### ISSUE THREAD

**Issue by wviana** [futurice/android-best-practices#111]
Hello,

I would add in Proguard session that for Proguard  really optimize the code you should change the line 
`proguardFiles getDefaultProguardFile('proguard-android.txt'),` to `proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),` ( add `-optimize` into the file name), when added it, the release build will take longer bug you'll get a really reduced apk.

Not sure, but looks like the need to add the `-optimize` ~point to optimize file~ begin in new version of android studio or Proguard. 

I had problems my self checking that Proguard was not doing what I was expecting, so I've found it.

**Comment by peter-tackage** [comment]
Most of the details of the Proguard files provided by the SDK and how they can be used via Gradle builds are covered in https://developer.android.com/studio/build/shrink-code.html. Rather than duplicating their specific detailed setup instructions, I think it would be better to provide that link along with any additional insights that we might have.

**Comment by wviana** [comment]
@peter-tackage Do you think these -optimize thing could be one of these "additional insights" ?

**Comment by peter-tackage** [comment]
Given that it's documented, I'm not convinced that it's necessary to discuss it in this document. I'm keen to focus on insights, rather than repeating what is in the SDK docs. (of course we're not perfect on this).
