### ISSUE TITLE
Roboelectric for unit testing?

### ISSUE THREAD

**Issue by luciapayo** [futurice/android-best-practices#115]
I was in the Droidcon a couple of days ago and there was a talk about why not to use Roboelectric. Basically what he said is that it makes the tests slow and when you use it only for unit testing and not for views (what we recommend), doesn't provide anything you could not do yourself. 

I don't have experience with Robolectric myself, I never needed it, if my class uses some Bundle or framework related stuff I just wrap it. 

So my question: is really a good practice to use Robolectric when it makes your tests slow and it is possible to live without it?

**Comment by peter-tackage** [comment]
I too have not used Roboletric in any significant way, but at the moment I can't see a place for it; given the improvement in JVM testing tools for Android and patterns such as MVP/MVVM that separate logic from platform dependencies. 

I can't comment on performance, but the real issue for me is that the tests run against an approximation of Android in code that you can't control. For all the boilerplate your get in wrapping, at least you control the contract. See #114

**Comment by jaggernod** [comment]
My biggest problem with using Roboletric is that it is provided by 3rd party company. So if you now have Android N then you still need for their implementation, which can take time and might not behave as a real device.
The other thing is that if you shouldn't use it for unit tests as those are not Unit test if you rely on the whole 3rd party implementation. For Integration Tests using the real software seems like a better idea.

P.S. Making your own code independent from Android framework will be also a good exercise.

**Comment by peter-tackage** [comment]
This is a good point about Robolectric having to play catchup with APIs and implementation.

**Comment by samiuelson** [comment]
Roboelectric is not a good approach to unit testing. App should be design in such way that business logic can be tested with junit and only some mocks. Use dependency injection in your app design, don't mess entities and business logic with android.* package classes.

**Comment by peter-tackage** [comment]
Sounds like we are all in agreement on this one.

**Comment by djodjoni** [comment]
there several statements here which are kind of too generic and not clear to me. 
First of all I am using Roboelectric and I hate it, but it is useful and I will share why :)

 @luciapayo roboelectric does not really make your tests that slow but probably the speed of development of those tests is slow, which is obvious. Also wrapping too much things will cost lots of time maintaining those wrappers.
 @peter-tackage there is no excuse for boilerplate :) so better somebody else do it, I hope they respect the contract as I hope the millions version of Android does too :)
@samiuelson dependency injection and mock should be used wisely and only if needed and too complicated other wise.

There is not question about that Business logic should be done is a way that it has almost and preferably no external dependencies, however there is also Application Specific Business Logic, which needs to be tested as well.

There is a bit confusion what is a Unit Test and the confusion is in 2 main points:
1) the definition of a Unit. and and in OOP is should not strictly mean a single Class. This involeves tightly the granularity of writing tests, if you go too far you are probably coupling with implementations or some internal parts of your system that doesn't really need to be separately tested.
2) the isolation of those tests. tests should be isolated in such a way that they do not interfere with each other. Isolating the Unit from its environment -> mocks -> (coupling with implementation , probability that it does not behave correctly in real environment)

Having said that Unit Tests may involve some android components. 
Some will say "..well wrap those", but this can be really costly for a line of code you may end up creating bunch of classes in different modules coupling with Android specifics anyway And still not covering the real UI test. What I learn from experience is that no-one care of your Unit Tests, they just want the app to run as in specs, its just you who needs to maintain those tests.

So 'Unit Tests may involve some android components'. 

Normally you should not mock 3rd party code(just the adapters connecting to it) as you don't know in detail how it works. Robolectric guys do exactly this and its pretty big one. They do an awesome job and yet I prefer test with a Real device using Espresso. The problem is using TDD and running tests constantly could be terribly slow so Roboelectric is of real help here. 

So Roboelectric can be used for unit tests which involves android components and its way faster than Espresso (the fastest currently real UI framework)

**Comment by AlejandroHCruz** [comment]
What about Espresso and the new [Espresso Test Recorder in Android Studio 2.2](http://android-developers.blogspot.mx/2016/05/android-studio-22-preview-new-ui.html)?

**Comment by djodjoni** [comment]
i tried the recording  and i like it. its a bit slow but quite  helpful. however i believe it is already mentined in  #114

**Comment by rhonyabdullah** [comment]
So can some explain when i should roboelectric and when i should espresso ? I'm confusing to choose the exactly testing tool.

**Comment by djodjoni** [comment]
IMO use roboelectric when you want UI related tests to pass fast for example during TDD cycles. 
Espresso you can use to run big set of integration tests overnight or limited set of acceptance tests for feature validation.

Note that the main idea is to spend less time in code and tests but do more features (test covered of course) . So if using some framework is taking to much time  to set up and run and the tests are flaky then you probably do not use it right or the framework is not meant to be used this way.
