### ISSUE TITLE
Cannot add a configuration with name 'testCompile' as a configuration with that name already exists. 

### ISSUE THREAD

**Issue by felipecaldas** [futurice/android-best-practices#120]
Hi all,

I cloned the project, opened with Android Studio and that's the error.

No other changes done.

Any ideas?

Thanks.

**Comment by peter-tackage** [comment]
Hi @felipecaldas. Thanks for the feedback. We're currently in the process creating a new demo project with more real-world requirements. I would consider the current version deprecated for now, given the number of Android Gradle plugin and Android Studio releases since it was originally created, this probably explains the breakage you have found.

**Comment by felipecaldas** [comment]
Thanks @peter-tackage  ! I will await for the new update then. Looking forward to it! Cheers.

**Comment by peter-tackage** [comment]
If you are interested in Android architecture and RxJava, then have a look at this library: https://github.com/reark/reark
