### ISSUE TITLE
RxJava - BookFragment

### ISSUE THREAD

**Issue by janswist** [futurice/android-best-practices#125]
In [this fragment](https://github.com/futurice/android-best-practices/blob/master/templates/rx-architecture/app/src/main/java/com/futurice/project/fragments/BookFragment.java) I can't see how after adding all three subscriptions they are all started.

I can see there `publish().refCount()` (which now can be switched to `share()`), but as far as I know, there should be `connect()` call to fire this (hot) obsevable.

**Comment by peter-tackage** [comment]
From my quick reading of the code, it does seem to miss that call. If you are interested in a more complete working example of RxJava 2, I can refer you to this project of ours instead - https://github.com/futurice/freesound-android. 

I've made a PR to remove the existing Rx template from this repo, because evidently it's dated and has its issues.
