### ISSUE TITLE
Recommend sharing your **debug** signing key

### ISSUE THREAD

**Issue by peter-tackage** [futurice/android-best-practices#158]
- Shared debug signing key makes working some remote API easier (e.g. Google Maps)
- Other scenarios?

**Comment by joan-domingo** [comment]
Sharing the debug apk signing key saves time when testing on shared devices and avoids the uninstalling/reinstalling of the app

**Comment by Kaila808** [comment]
On Jul 16, 2017 5:16 AM, "Peter Tackage" <notifications@github.com> wrote:


   - Shared debug signing key makes working some remote API easier (e.g.
   Google Maps)
   - Other scenarios?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/futurice/android-best-practices/issues/158>, or mute
the thread
