### ISSUE TITLE
Can I learn Android Development in Java as a beginner?

### ISSUE THREAD

**Issue by anirudh-hegde** [futurice/android-best-practices#206]

**Comment by Danc-0** [comment]
Hello @Anianonymous, yeah you can still learn Java for Android Development, which ideally would be kind of starting from the bottom on how it was. 

Now the question is which projects will you be working on once done with learning, maybe maintaining old legacy android code am not sure, for how long you will do that noting that most projects are either being migrated to Kotlin or are being completely rebuilt with Kotlin, there now comes the need to learn Kotlin and also the need to keep up with the latest trends in Android because currently its the recommended language by Google for Android.

What I will advice is you already know Java, just learn Kotlin and Kotlin for Android, it will make things easier for you in the long run.

**Comment by anirudh-hegde** [comment]
> Hello @Anianonymous, yeah you can still learn Java for Android Development, which ideally would be kind of starting from the bottom on how it was.
> 
> Now the question is which projects will you be working on once done with learning, maybe maintaining old legacy android code am not sure, for how long you will do that noting that most projects are either being migrated to Kotlin or are being completely rebuilt with Kotlin, there now comes the need to learn Kotlin and also the need to keep up with the latest trends in Android because currently its the recommended language by Google for Android.
> 
> What I will advice is you already know Java, just learn Kotlin and Kotlin for Android, it will make things easier for you in the long run.

Thank you @Danc-0
