### ISSUE TITLE
Testing examples in the Project Template

### ISSUE THREAD

**Issue by kaushikgopal** [futurice/android-best-practices#27]
The project template architecture is pretty nice in demonstrating a clean architecture pattern with RxJava.  

It would be nice to see more real-world testing examples, as there seems to be a dearth of those. The ones included help ensuring the test framework works, but more flushed out examples would be nice.

**Comment by peter-tackage** [comment]
@kaushikgopal It's been a while, but to answer your questions. Yes, we would recommend using `TestScheduler` and also `TestSubscriber` when testing apps written with Rx.
 
For example, when testing MVVM we do the following when unit testing the ViewModel:
* Keep ViewModel free of Android dependencies.
* Mock collaborators using Mockito.
* Use `TestScheduler` instances.
* Test the ViewModel public API using `TestScheduler`, avoiding testing internal implementations.

Using Blocking Observable for testing is flawed because the time based operations can't be accelerated. The unit test below will take an hour to run, which not ideal!

```java
    public Observable<String> delayObservable() {
        return Observable.just("a value")
                         .doOnNext(System.out::print)
                         .delay(1, TimeUnit.HOURS)
                         .doOnNext(__ -> System.out.println("Done"));
    }

    @Test
    public void testDelayObservable_usingBlocking() {
        delayObservable().toBlocking().subscribe(it -> System.out.print("Finished in Subscriber"));
    }
```

I'm writing some articles at the moment that go into a bit more detail.

**Comment by peter-tackage** [comment]
See #114

**Comment by jaggernod** [comment]
@kaushikgopal another issue with ````toBlocking``` except the one that @peter-tackage mentioned is that you are prohibiting yourself from using ```TestSubscriber```. Of course, the verification part in cool but without ```TestSubscriber``` one cannot easily test for backpressure support of your Observables.
