### ISSUE TITLE
ViewPager inside ViewPager

### ISSUE THREAD

**Issue by ppamorim** [futurice/android-best-practices#46]
Hi, anyone know if nested ViewPager can be a problem?
I've implemented this on my app and I have a huge increment of performace and non blocking UI, Because it avoid replace or add fragment every time when I need change the content.
I have created a NonSwipeableViewPager and added a normal ViewPager inside it. When the user select a item on NavigationDrawer, the NonSwipeableViewPager slide to position of the content.

**Comment by peter-tackage** [comment]
To me, it sounds like a fairly unconventional approach. I can see a few downsides to it. Firstly, using a ViewPager then suppressing the primary elements of its behavior is probably wasteful and you may create bugs in doing so. Secondly, I can imagine that it could result in excess memory consumption, due to the ViewPager keeping Fragments/Views in memory (in +/- 1 positions) to support its typical paging behavior. The performance benefit observed may be a result of the ViewPager having already created the content before the request to display it is made.

As you are probably aware, the same effect could be achieved by using a simple ViewGroup container and swapping in/out the content with the appropriate animation. That way you free yourself from having to maintain the ViewPager apparatus.

Depending on your circumstances, you may regard the performance benefits you have observed as a worthwhile tradeoff for the memory consumption and possible maintenance complications. Personally, I'd use a more conventional approach and investigate the causes of the UI blocking.
