### ISSUE TITLE
Extend testing frameworks

### ISSUE THREAD

**Issue by brave-warrior** [futurice/android-best-practices#99]
Would be nice to have a section with best practices for using unit testing frameworks (JUnit, Mockito)

**Comment by peter-tackage** [comment]
Agreed @brave-warrior. This has been on my backlog for a while as the landscape has certainly changed since the initial version of this document.

**Comment by peter-tackage** [comment]
As a brief summary of my thoughts how to write tests:

- Minimize explicit Android dependencies in your code through abstraction and separation of concerns. Android dependencies require you to use instrumentation tests, which are considerably slower than strictly Java (JVM) based tests.
- Start with unit tests, driven by JUnit4.
- Use Mockito for mock definitions
- Use descriptive names for the unit test to aid in defining expected behavior.
- Use good test structure: Arrange, Act, Asset.
- Separate arrangement definitions into an "arrange builder" to improve test readability.
- Use AssertJ for assertions.
- Add integration and UI tests once their business value is justified.
- Use PowerMock for mocking statics and final classes as a last resort.
- Be aware that pure Java unit testing has its limits, and that writing specific Android tests still remains important in some cases - for example; database handling.

@tomaszpolanski might have some input here too.

**Comment by tomaszpolanski** [comment]
When using Rx and "scheduled" observable, either inject schedulers or something that provides them.
Then in test you can use TestScheduler to test timer related functionality.

**Comment by brave-warrior** [comment]
@peter-tackage agree with your points. But would extend the following items with the links to appropriate resources or detailed description:
> - Use Mockito for mock definitions

add link for Mockito; the recommendations how to mock objects and the check behaviour in the better/best way
> - Use AssertJ for assertions.

Link to AssertJ would be good and what are the advantages of that
> - Add integration and UI tests once their business value is justified.

not clear enough

The other points are quite clear and could be added to the best practices.

**Comment by peter-tackage** [comment]
@tomaszpolanski Agreed. Testing Rx is probably worth it's own section.

**Comment by peter-tackage** [comment]
@brave-warrior I'll be progressing the testing section update under #114
